package com.ydzw.smartim.mapper;

import com.ydzw.smartim.model.UserInfo;
import com.ydzw.smartim.model.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    UserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    int updateByPrimaryKey(UserInfo record);
}