package com.ydzw.smartim.model;

public class UserInfo {

    private String userId;

    private String userPassword;

    private String userName;

    private String userCompany;

    private String userPostition;

    private Integer idReviewestatus;

    private String userType;

    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Id
     *
     * @param userId the value for user_infor.User_Id
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.User_Password
     *
     * @return the value of user_infor.User_Password
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Password
     *
     * @param userPassword the value for user_infor.User_Password
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword == null ? null : userPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.User_Name
     *
     * @return the value of user_infor.User_Name
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Name
     *
     * @param userName the value for user_infor.User_Name
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.User_Company
     *
     * @return the value of user_infor.User_Company
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getUserCompany() {
        return userCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Company
     *
     * @param userCompany the value for user_infor.User_Company
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserCompany(String userCompany) {
        this.userCompany = userCompany == null ? null : userCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.User_Postition
     *
     * @return the value of user_infor.User_Postition
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getUserPostition() {
        return userPostition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Postition
     *
     * @param userPostition the value for user_infor.User_Postition
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserPostition(String userPostition) {
        this.userPostition = userPostition == null ? null : userPostition.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.ID_RevieweStatus
     *
     * @return the value of user_infor.ID_RevieweStatus
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public Integer getIdReviewestatus() {
        return idReviewestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.ID_RevieweStatus
     *
     * @param idReviewestatus the value for user_infor.ID_RevieweStatus
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setIdReviewestatus(Integer idReviewestatus) {
        this.idReviewestatus = idReviewestatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_infor.User_Type
     *
     * @return the value of user_infor.User_Type
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getUserType() {
        return userType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_infor.User_Type
     *
     * @param userType the value for user_infor.User_Type
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setUserType(String userType) {
        this.userType = userType == null ? null : userType.trim();
    }
}