package com.ydzw.smartim.model;

import java.util.ArrayList;
import java.util.List;

public class UserInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public UserInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("User_Id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("User_Id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("User_Id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("User_Id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("User_Id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("User_Id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("User_Id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("User_Id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("User_Id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("User_Id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("User_Id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("User_Id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("User_Id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNull() {
            addCriterion("User_Password is null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIsNotNull() {
            addCriterion("User_Password is not null");
            return (Criteria) this;
        }

        public Criteria andUserPasswordEqualTo(String value) {
            addCriterion("User_Password =", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotEqualTo(String value) {
            addCriterion("User_Password <>", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThan(String value) {
            addCriterion("User_Password >", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("User_Password >=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThan(String value) {
            addCriterion("User_Password <", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLessThanOrEqualTo(String value) {
            addCriterion("User_Password <=", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordLike(String value) {
            addCriterion("User_Password like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotLike(String value) {
            addCriterion("User_Password not like", value, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordIn(List<String> values) {
            addCriterion("User_Password in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotIn(List<String> values) {
            addCriterion("User_Password not in", values, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordBetween(String value1, String value2) {
            addCriterion("User_Password between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserPasswordNotBetween(String value1, String value2) {
            addCriterion("User_Password not between", value1, value2, "userPassword");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("User_Name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("User_Name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("User_Name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("User_Name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("User_Name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("User_Name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("User_Name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("User_Name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("User_Name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("User_Name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("User_Name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("User_Name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("User_Name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("User_Name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIsNull() {
            addCriterion("User_Company is null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIsNotNull() {
            addCriterion("User_Company is not null");
            return (Criteria) this;
        }

        public Criteria andUserCompanyEqualTo(String value) {
            addCriterion("User_Company =", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotEqualTo(String value) {
            addCriterion("User_Company <>", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyGreaterThan(String value) {
            addCriterion("User_Company >", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyGreaterThanOrEqualTo(String value) {
            addCriterion("User_Company >=", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLessThan(String value) {
            addCriterion("User_Company <", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLessThanOrEqualTo(String value) {
            addCriterion("User_Company <=", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyLike(String value) {
            addCriterion("User_Company like", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotLike(String value) {
            addCriterion("User_Company not like", value, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyIn(List<String> values) {
            addCriterion("User_Company in", values, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotIn(List<String> values) {
            addCriterion("User_Company not in", values, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyBetween(String value1, String value2) {
            addCriterion("User_Company between", value1, value2, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserCompanyNotBetween(String value1, String value2) {
            addCriterion("User_Company not between", value1, value2, "userCompany");
            return (Criteria) this;
        }

        public Criteria andUserPostitionIsNull() {
            addCriterion("User_Postition is null");
            return (Criteria) this;
        }

        public Criteria andUserPostitionIsNotNull() {
            addCriterion("User_Postition is not null");
            return (Criteria) this;
        }

        public Criteria andUserPostitionEqualTo(String value) {
            addCriterion("User_Postition =", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionNotEqualTo(String value) {
            addCriterion("User_Postition <>", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionGreaterThan(String value) {
            addCriterion("User_Postition >", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionGreaterThanOrEqualTo(String value) {
            addCriterion("User_Postition >=", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionLessThan(String value) {
            addCriterion("User_Postition <", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionLessThanOrEqualTo(String value) {
            addCriterion("User_Postition <=", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionLike(String value) {
            addCriterion("User_Postition like", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionNotLike(String value) {
            addCriterion("User_Postition not like", value, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionIn(List<String> values) {
            addCriterion("User_Postition in", values, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionNotIn(List<String> values) {
            addCriterion("User_Postition not in", values, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionBetween(String value1, String value2) {
            addCriterion("User_Postition between", value1, value2, "userPostition");
            return (Criteria) this;
        }

        public Criteria andUserPostitionNotBetween(String value1, String value2) {
            addCriterion("User_Postition not between", value1, value2, "userPostition");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusIsNull() {
            addCriterion("ID_RevieweStatus is null");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusIsNotNull() {
            addCriterion("ID_RevieweStatus is not null");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusEqualTo(Integer value) {
            addCriterion("ID_RevieweStatus =", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusNotEqualTo(Integer value) {
            addCriterion("ID_RevieweStatus <>", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusGreaterThan(Integer value) {
            addCriterion("ID_RevieweStatus >", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("ID_RevieweStatus >=", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusLessThan(Integer value) {
            addCriterion("ID_RevieweStatus <", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusLessThanOrEqualTo(Integer value) {
            addCriterion("ID_RevieweStatus <=", value, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusIn(List<Integer> values) {
            addCriterion("ID_RevieweStatus in", values, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusNotIn(List<Integer> values) {
            addCriterion("ID_RevieweStatus not in", values, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusBetween(Integer value1, Integer value2) {
            addCriterion("ID_RevieweStatus between", value1, value2, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andIdReviewestatusNotBetween(Integer value1, Integer value2) {
            addCriterion("ID_RevieweStatus not between", value1, value2, "idReviewestatus");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNull() {
            addCriterion("User_Type is null");
            return (Criteria) this;
        }

        public Criteria andUserTypeIsNotNull() {
            addCriterion("User_Type is not null");
            return (Criteria) this;
        }

        public Criteria andUserTypeEqualTo(String value) {
            addCriterion("User_Type =", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotEqualTo(String value) {
            addCriterion("User_Type <>", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThan(String value) {
            addCriterion("User_Type >", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeGreaterThanOrEqualTo(String value) {
            addCriterion("User_Type >=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThan(String value) {
            addCriterion("User_Type <", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLessThanOrEqualTo(String value) {
            addCriterion("User_Type <=", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeLike(String value) {
            addCriterion("User_Type like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotLike(String value) {
            addCriterion("User_Type not like", value, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeIn(List<String> values) {
            addCriterion("User_Type in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotIn(List<String> values) {
            addCriterion("User_Type not in", values, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeBetween(String value1, String value2) {
            addCriterion("User_Type between", value1, value2, "userType");
            return (Criteria) this;
        }

        public Criteria andUserTypeNotBetween(String value1, String value2) {
            addCriterion("User_Type not between", value1, value2, "userType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_infor
     *
     * @mbg.generated do_not_delete_during_merge Fri Dec 20 16:53:04 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_infor
     *
     * @mbg.generated Fri Dec 20 16:53:04 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}